alias vi="/c/Program\ Files\ \(x86\)/Vim/vim74/gvim.exe"
alias vim="/c/Program\ Files\ \(x86\)/Vim/vim74/gvim.exe"
alias gvim="/c/Program\ Files\ \(x86\)/Vim/vim74/gvim.exe"
MDP="/c/Program\ Files\ \(x86\)/MarkdownPad\ 2/MarkdownPad2.exe"
alias markdownpad="$MDP"
alias mdp="$MDP"
alias code='cd ~/Documents/git'
alias website='cd ~/Documents/git/asciamanna.github.io'
alias configs='cd ~/Documents/git/configs'
