#alias grep='grep --color' #msysgit's grep doesn't recognize color
alias vi="/c/Program\ Files\ \(x86\)/Vim/vim74/gvim.exe"
alias vim="/c/Program\ Files\ \(x86\)/Vim/vim74/gvim.exe"
alias gvim="/c/Program\ Files\ \(x86\)/Vim/vim74/gvim.exe"
alias python="/c/python27/python.exe"
alias markdownpad="~/AppData/Local/Programs/MarkdownPad' '2/MarkdownPad2.exe"
alias mdp="~/AppData/Local/Programs/MarkdownPad' '2/MarkdownPad2.exe"
alias code='cd ~/Documents/GitHub'
alias website='cd ~/Documents/GitHub/asciamanna.github.io'
alias configs='cd ~/Documents/GitHub/configs'
