set nocompatible
source $VIMRUNTIME/vimrc_example.vim
"don't source mswin.vim - changes vim behavior
"source $VIMRUNTIME/mswin.vim
behave mswin

"custom settings
execute pathogen#infect()
set title
set tabstop=2 shiftwidth=2 softtabstop=2 expandtab
set showmode
set nu
set showmatch
set incsearch
set hlsearch
set ignorecase
set smartcase
set autoindent
set nobackup
syntax enable
syntax on
filetype plugin indent on
set background=dark
colorscheme solarized
set noeb vb t_vb=
set nrformats=

if has('gui_running')
	set guioptions-=T
end
